version: "3.11"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:15
    volumes:
      - $HOME/postgresql/data_two:/var/lib/postgresql/data_two
    ports:
      - "5432:5432"
    env_file: .env
